import Head from 'next/head'


export default function Home() {
  return (
    <>
      <div className="flex flex-col items-center justify-center min-h-screen">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Hello world</h1>      
      </div>
    </>
  )
}
